# Generated by Django 5.0 on 2023-12-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='email',
        ),
    ]
